# 标定结果写出到bag同级同名文件夹

lid_decode:
  lidar_file_path: E:\data\outdoor\b1_b1-07221901\data\Lidar
  imu_file_path:   E:\\data\\outdoor\\b1_b1-07221901\\data\\Pos\\20240722110223_IMU.txt
lid_params:
  lidar_send_duration: 1 # 雷达帧率
  #min_detect_distance: 0 # 最小过滤
  #max_detect_distance: 100 # 最大过滤
  start_process_time: 0    # 开始时间
  #end_process_time:   100  # 结束时间
  start_process_id:  10     #开始帧id
  end_process_id:    50 # 结束帧id
  #lidar_send_duration: 100000  #处理时间
  
  
calibration_config:
   optimize_motor_intrisinc_param: true         # 优化编码器内参：alpha1, alpha2, dP
   optimize_motor_angle_correct_param: true     # 优化编码器360个角度修正量
   optimize_lidar_intrisinc_param: false         # 优化激光器内参：16个垂直角
   
bag_decode:
   bag_path: D:\code\01.sensor_calibrate\data\2022-12-01-13-47-14.bag
   srcpts_path: D:\code\01.sensor_calibrate\data\04\202404090510-RawLidar00001.txt
   lidar_topic: /hesai/pandar_packets
   motor_topic: /GV_MotorConfig

   # process_duration: 10         # 标定处理范围，默认以编码器开始旋转后的process_duration秒的数据用于标定
   
   # 以下参数若不指定，默认全部解码，这个可以指定处理范围，和上面的有一点冲突
   start_process_time: 70
   end_process_time: 80
   
   # 若不指定起止处理id，需要注释掉
   # start_process_id: 
   # end_process_id: 
   
   # 范围过滤原始bag解码数据
   min_detect_distance: 0.5
   max_detect_distance: 100

motor_intrinsic_parameter:
#    alpha1: -0.144199
#    alpha2: -0.136248
#alpha3: 0.000000
#    dp: [0.000911, -0.008969, 0.000000]

    alpha1:     0.1094 #-0.0053     
    alpha2:     0.1696  #0.0055
    alpha3:     0.000000
    dp: [-0.00, -0.0150, 0.000000]

    rotLidar2Motor: [-1, 0, 0, 0,  0, 0, -1,0, 0, -1, 0,0, 0, 0, 0, 1]

motor_angle_calibration_parameter:
  # 若不设置，则默认360个角度修正值为0
  angle_correction_file: D:\code\01.sensor_calibrate\data\01\motor_angle_correction_param.txt
  lidar_intrisic_file: D:\code\01.sensor_calibrate\data\01\lidar_intrisic_param.txt
  # 这个可以不用，默认标所有线
  # calibration_laser_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]